### ISSUE TITLE
Driving the keypad from the uC

### ISSUE THREAD

**Issue by rooprob** [RHash67/fbii-xl2t#3]
First, thanks for this.  I have a FBII STAR XL4500 and XL4500RM keypad.  My uC is an ESP8266.  

The circuit is on a breadboard and I have the 12v reduced to 3.3v for the ESP. Arduino compiled the code, and I've made some small tweaks but it's basically working as-is. Nice!

I can read the status and LEDs with this project, but sendKey is not.
No errors and I see a little signal on Q3.

This is where my understanding breaks down. 

How does the signal get put back to the yellow data line from the uC?

I'm trying to work out the purpose of R8. 

I don't understand the Shunt. I'm trying to understand how writing to Shunt can put a 12v signal on Data line. 

I'm only getting 3.3v out of the 

I'll need to get more detailed testing.

Thanks for any pointers! 
Good job on the code! I guess there are now two people adding WiFi to their 20yo alarms.

**Comment by RHash67** [comment]
The keypress data is sent to the system by controlling the level of the data line during the low clock pulses.  If the shunt control is switched to its low level, then Q3 will be off, and the data line will remain high.  If the shunt control is switched high, then Q3 will turn on, and the data line will be forced to ground level (low).  The keypress signal is not “put onto” the data line – rather, the data line is just kept high or sent low (during the low clock pulses) to “send” the data.

R8 is there mostly for circuit stability.  If the shunt control level is floating for any reason (e.g. during circuit startup, or gets disconnected), R8 will ensure that Q3 is off, so it doesn’t affect the value of the data line during the read portion of the clock signal.

For my system I need to use transistors to interface the clock, data, and shunt because my alarm panel (FBII XL-2T) has the clock and data at +12V - +15V range.  If I try to connect those directly to my uC I will burn it out.  I’m not familiar with your FBII SA4500 system, but if your clock and data signals are at 3.3V levels, then you might be able to monitor the clock and data lines via direct connection to your uC without using transistors.  If you do this you will need to modify the code to invert the logic levels, since the transistors invert the logic levels between their base and collector.  In the XL2T_Interface.cpp code, the _pulselvl and _signallvl variables are used to read the logic level of the signals.  If you read the signals directly, then you will need to modify the conditional tests (e.g. instead of testing == 0, would need to test == 1), and possibly modify code sections which invert the bits.  You will still probably still need a transistor for the shunt control in order to isolate it from the data line.

When I started this project I could not determine if the data stream followed any standardized format (e.g. RS-232, etc, which it does not).  Luckily the clock pulse period is rather long (0.5 ms), so I could easily capture the pulses with my digital oscope to reverse-engineer the signals.  Also, the clock pulses are slow enough where the code just relies on looking for the rising/falling edges of the clock, and counting the pulses.  I know this is not very sophisticated, but hey – it works!  😊

Good luck on your system interface!  I'm glad that someone has found this useful!

**Comment by RHash67** [comment]
Also, keep in mind that a minimum of 2 identical keypress data needs to be sent in adjacent data packets to be considered a valid keypress.  The arduino code handles this via a simple loop for the keypress routine.

**Comment by rooprob** [comment]
Thanks @RHash67 

Thanks for your reply.   I can see how the shunt circuit works now, and I'm pleased to say it's all working well for me now.

Turns out the XL2T and the SA4500 are pretty much the same electrically and signalling. I get pretty much identical Alarm Status codes as you do.  My keypad does have different keycodes, and following your idea they are scattered around in the uint32_t as an obscurity, I have now successfully decoded, and I can send them back into the alarm to Arm it. 

I had to make a few adjustments on this journey.
* read the keycode along with the alarm status during the readAllStatus()
* add the helper functions to read the alarm status bits from status value, rather than re-probing for them
* added a microsecond sleeps to try and put the bit-reading code directly in the middle of the 250us clock signal - the issue I had was I was reading the trailing edge and getting a lot of  jitter - maybe my Arduino is a bit faster or my wiring a bit noisy. 

This clunky old alarm gets a useful IoT modernization. It will be taking up residence in the workshed. 

Can consider this issue closed :)

**Comment by RHash67** [comment]
Glad you were able to get your interface working!

It didn't occur to me that different FBII systems could have different keycode values.  Somewhere in my files I have a test sketch to display the keycode hex values on an LCD screen hooked up to the arduino - I should post it here (hopefully I've kept it somewhere).  I forgot I had used this as a "digital oscope" to capture the signal values.  I do have a "real" oscope, but it's not sophisticated enough to record waveforms on trigger events.  The test sketch I made was very handy in displaying the hex values associated with each keypress.

I'm happy to see at least one other clunky old alarm meeting the modern world!  :D
